project:
  type: book

book:
  title: "Interventionsstudien sinnvoll planen"
  author: "Carolin Baumann"
  chapters:
    - index.qmd   
    - theorie_beginn.qmd                 # Einleitung
    - design.qmd                   # Experimentelles Design
    - kontrollgruppe.qmd           # Kontrollgruppen (gehört zu Design)
    - stichprobe.qmd               # Stichprobenziehung
    - poweranalyse_erweitert.qmd            # Wie groß muss die Stichprobe sein?
    - randomisierung.qmd   
    - validität.qmd        # Wie teile ich die Stichprobe ein?
    - aufgaben.qmd  
    
format:
  html:
    toc: true
    theme: default

execute:
  echo: false
  warning: false
  message: false

editor: source
