# Bedrohungen der internen Validität

In der Campbell-Tradition werden neun Bedrohungen der internen Validität unterschieden (Cook & Campbell, 1979; Shadish et al., 2002). Diese Bedrohungen führen dazu, dass ein statistisch nachgewiesener Zusammenhang zwischen Variablen nicht eindeutig als Ursache-Wirkungs-Zusammenhang interpretiert werden kann.

## 1. Unklare zeitliche Abfolge

Ein kausaler Ursachenfaktor muss zeitlich immer der Wirkung vorgelagert sein. Bei nicht-experimentellen korrelativen Studien, in denen potenzielle Ursachenfaktoren gleichzeitig mit den abhängigen Variablen gemessen werden, kann es bei der kausalen Interpretation zu Fehlern kommen. Die Kausalrichtung könnte verkehrt herum behauptet oder wechselseitige kausale Beeinflussung könnte übersehen werden.

## 2. Selektionseffekte

Unterscheiden sich die Untersuchungspersonen in den einzelnen Gruppen bereits vor der Behandlung, so können diese bereits bestehenden Unterschiede später fälschlich als kausale Treatmentwirkung interpretiert werden.

## 3. Externe zeitliche Einflüsse

Geht das untersuchte Treatment mit anderen, untersuchungsunabhängigen äußeren Veränderungen in den situativen oder Umweltvariablen der Untersuchungspersonen einher, so können letztere fälschlich als kausaler Treatmenteffekt interpretiert werden.

## 4. Reifungsprozesse

Da sich Untersuchungspersonen im Verlauf der Zeit von ganz allein in ihren Zuständen und Merkmalen verändern (z. B. älter, reifer, kränker, gesünder werden), können diese Reifungsprozesse fälschlich als kausale Treatmenteffekte interpretiert werden.

## 5. Statistische Regressionseffekte

Werden für eine Studie Personen mit extrem hohen oder extrem niedrigen Merkmalsausprägungen ausgesucht, so ist bei wiederholter Messung automatisch eine Tendenz zur Mitte zu erwarten. Dieser statistische Regressionseffekt kann fälschlich als kausale Treatmentwirkung interpretiert werden.

## 6. Experimentelle Mortalität

Im Verlaufe einer Studie fallen immer wieder Untersuchungspersonen aus. Wenn ein Vorher-Nachher-Vergleich nicht auf derselben Gruppe basiert, sondern aus der Nachher-Gruppe selektiv bestimmte Personen herausgefallen sind, kann dieser Mortalitätseffekt fälschlich als kausaler Treatmenteffekt interpretiert werden.

## 7. Testübung

Wird im Zuge einer Studie mehrfach dasselbe Messinstrument eingesetzt, kann die Erfahrung mit dem Instrument das Antwortverhalten der Untersuchungspersonen verändern. Dieser Testübungseffekt kann fälschlich als kausale Treatmentwirkung interpretiert werden.

## 8. Mangelnde instrumentelle Reliabilität

Im Verlaufe der Zeit kann sich die Qualität eines Messinstrumentes verändern, so dass Messwertunterschiede entstehen, die fälschlich als kausale Treatmentwirkung interpretiert werden können.

## 9. Kombination mehrerer Bedrohungen

Die acht vorgenannten Bedrohungen der internen Validität können auch in Kombination wirksam sein und dabei additiv oder in anderer Weise zusammenwirken.
